services:

  dev-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: dev-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: eharo
      RABBITMQ_DEFAULT_PASS: 12341234
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persistencia de datos
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - poisonus-network

  dev-db:
    image: mysql
    container_name: dev-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: eharo
      MYSQL_PASSWORD: 12341234
      MYSQL_DATABASE: poisonus
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - poisonus-network

  dev-phpmyadmin:
    image: phpmyadmin
    container_name: dev-phpmyadmin
    depends_on:
      - dev-db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: dev-db
    networks:
      - poisonus-network

  dev-php:
    build:
      context: .
      dockerfile: environment/development/docker/php.Dockerfile
    container_name: dev-php
    volumes:
      - .:/var/www/html
      - ./environment/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
    networks:
      - poisonus-network

  dev-nginx:
    build:
      context: .
      dockerfile: environment/development/docker/nginx.Dockerfile
    container_name: dev-nginx
    depends_on:
      - dev-php
    volumes:
      - .:/var/www/html
      - ./environment/development/virtualhosts:/etc/nginx/conf.d
    ports:
      - '82:80'
    networks:
      - poisonus-network

networks:
  poisonus-network:

volumes:
  db-data:
  rabbitmq-data: