parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags: [ 'app.command_handler' ]
        App\Shared\Domain\Bus\Query\QueryHandler:
            tags: [ 'app.query_handler' ]
        App\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: [ 'app.domain_event_subscriber' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Shared\:
        resource: '../src/Shared'

    App\Backoffice\:
        resource: '../src/Backoffice'

    App\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        - !tagged_iterator app.command_handler
    App\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        - !tagged_iterator app.query_handler
    App\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        - !tagged_iterator app.domain_event_subscriber
    App\Shared\Infrastructure\Symfony\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 60 }
    App\Shared\Infrastructure\Symfony\HttpAuthMiddleware:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    Doctrine\ORM\EntityManagerInterface:
        factory: [ App\Shared\Infrastructure\Persistence\Doctrine\EntityManagerFactory, create ]
        arguments:
            - driver: '%env(MYSQL_DRIVER)%'
              host: '%env(MYSQL_HOST)%'
              port: '%env(MYSQL_PORT)%'
              dbname: '%env(MYSQL_DB)%'
              user: '%env(MYSQL_USER)%'
              password: '%env(MYSQL_PASSWORD)%'
            - '%env(APP_ENV)%'
        public: true
